version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: public_data_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: public_data
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: public_data_phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql

volumes:
  mysql_data: 